# Generated by Django 5.0.4 on 2024-05-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extended_user.department', verbose_name='Головное подразделение')),
            ],
            options={
                'verbose_name': 'структурное подразделение',
                'verbose_name_plural': 'структурные подразделения',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание профиля')),
                ('post', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('communication', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контакты')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля')),
                ('manager', models.BooleanField(default=False, verbose_name='Менеджер')),
                ('authoring', models.BooleanField(default=False, verbose_name='Составитель курсов')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extended_user.department', verbose_name='Структурное подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'unique_together': {('name', 'surname', 'patronymic')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_author', to='extended_user.profile', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_by_chief', to='extended_user.profile', verbose_name='Начальник'),
        ),
        migrations.AddField(
            model_name='department',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_editors', to='extended_user.profile', verbose_name='Автор последних изменений'),
        ),
    ]
