# Generated by Django 5.0.4 on 2024-05-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('percent', models.IntegerField(verbose_name='Требуемое количество процентов')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл шаблона')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_author', to='extended_user.profile', verbose_name='Автор')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.course', verbose_name='Курс')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_editors', to='extended_user.profile', verbose_name='Автор последних изменений')),
            ],
            options={
                'verbose_name': 'вариант сертификата',
                'verbose_name_plural': 'варианты сертификатов',
                'ordering': ('-course', '-percent'),
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('Генерация', 'Генерация'), ('Сгенерирован', 'Сгенерирован'), ('Ошибка генерации', 'Ошибка генерации'), ('С предупреждениями', 'С предупреждениями')], default='in_progress', max_length=1024, verbose_name='Статус')),
                ('error', models.CharField(default='', max_length=4096)),
                ('last_operation_time', models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение')),
                ('last_version', models.BooleanField(default=True, verbose_name='Последняя версия')),
                ('warnings', models.TextField(blank=True, null=True, verbose_name='Предупреждения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_author', to='extended_user.profile', verbose_name='Автор')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson.course')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.demand', verbose_name='Основание')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_editors', to='extended_user.profile', verbose_name='Автор последних изменений')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-last_operation_time',),
            },
        ),
    ]
