# Generated by Django 5.0.4 on 2024-05-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент выполнения курса'),
        ),
    ]
