# Generated by Django 5.0.4 on 2024-05-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_generateddocument_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
