# Generated by Django 5.0.4 on 2024-05-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_author', to='extended_user.profile', verbose_name='Автор')),
                ('editors', models.ManyToManyField(to='extended_user.profile', verbose_name='Могут редактировать')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_editors', to='extended_user.profile', verbose_name='Автор последних изменений')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_author', to='extended_user.profile', verbose_name='Автор')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_editors', to='extended_user.profile', verbose_name='Автор последних изменений')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.course', verbose_name='Курс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_author', to='extended_user.profile', verbose_name='Автор')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.block', verbose_name='Блок')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_editors', to='extended_user.profile', verbose_name='Автор последних изменений')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
