# Generated by Django 5.0.4 on 2024-05-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='autotest',
            field=models.BooleanField(default=True, verbose_name='Автоматическая проверка'),
        ),
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='task',
            name='max_mark',
            field=models.IntegerField(default=5, verbose_name='Максимальный балл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='need_file',
            field=models.BooleanField(default=False, verbose_name='Можно приложить файл'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('новый', 'новый'), ('на проверке', 'на проверке'), ('оценен', 'оценен')], default='на проверке', max_length=127)),
                ('answer', models.TextField(null=True, verbose_name='Правильный ответ')),
                ('mark', models.IntegerField(verbose_name='Максимальный балл')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Прикрепленный файл')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_author', to='extended_user.profile', verbose_name='Автор')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_editors', to='extended_user.profile', verbose_name='Автор последних изменений')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
