# Generated by Django 5.0.4 on 2024-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_task_autotest_task_correct_answer_task_max_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Обложка'),
        ),
    ]
