# Generated by Django 5.0.4 on 2024-05-03 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
        ('lesson', '0003_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.course', verbose_name='Курс')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extended_user.profile', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
