# Generated by Django 5.0.4 on 2024-05-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_courseregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_options',
            field=models.TextField(blank=True, null=True, verbose_name='Варианты ответа'),
        ),
        migrations.AddField(
            model_name='task',
            name='correct_options_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный ответ (из вариантов)'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('текст', 'текст'), ('Одиночный выбор', 'Одиночный выбор')], default='текст', max_length=127, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='mark',
            field=models.IntegerField(verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный ответ (текст)'),
        ),
    ]
