# Generated by Django 5.0.4 on 2024-05-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_task_answer_options_task_correct_options_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='mark',
            field=models.IntegerField(default=0, verbose_name='Балл'),
        ),
    ]
