# Generated by Django 5.0.4 on 2024-05-04 08:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=ckeditor.fields.RichTextField(default=0, verbose_name='Ответ'),
            preserve_default=False,
        ),
    ]
